-- Fase 1 da integração Strava -> painel-saude.
-- Cole este script inteiro no Supabase (Dashboard -> SQL Editor -> New query -> Run).
-- Cria as tabelas `activities` (corrida/caminhada vindas do Strava) e `strava_tokens`
-- (tokens OAuth, um por usuário), com Row Level Security no mesmo padrão das
-- tabelas já existentes (bp_readings, body_weight, workout_sessions, profiles).

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  strava_activity_id bigint not null,
  type text not null check (type in ('Run', 'Walk')),
  start_date timestamptz not null,
  distance_m numeric,
  moving_time_s integer,
  average_heartrate numeric,
  max_heartrate numeric,
  average_speed numeric,
  created_at timestamptz not null default now(),
  unique (user_id, strava_activity_id)
);

create index if not exists activities_user_id_start_date_idx
  on public.activities (user_id, start_date);

alter table public.activities enable row level security;

-- Cada usuário só enxerga as próprias atividades. Não há política de
-- insert/update/delete para o cliente: quem grava é a Edge Function (Fase 3),
-- usando a service role key, que ignora RLS por padrão.
create policy "activities: usuário lê as próprias atividades"
  on public.activities for select
  using (auth.uid() = user_id);

-- Tokens do Strava. Fica sem NENHUMA policy de propósito: RLS ligado e zero
-- políticas significa que ninguém acessa via cliente (anon/authenticated),
-- nem o dono da linha -- só a service role key (usada pela Edge Function)
-- enxerga isto, já que são segredos e não precisam nunca aparecer no navegador.
create table if not exists public.strava_tokens (
  user_id uuid primary key references auth.users(id) on delete cascade,
  athlete_id bigint not null,
  access_token text not null,
  refresh_token text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.strava_tokens enable row level security;
